package com.framework.context;

import lombok.Data;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.HashMap;
import java.util.Map;

/**
 * Thread-local shared state bag for a single test execution.
 *
 * This is THE bridge between API and UI steps in a hybrid test.
 *
 * WHY THIS EXISTS:
 *   When a test creates a user via API and then validates via UI, the
 *   userId / token / email generated by the API call must be passed to
 *   the UI step in the same thread. TestContext is that conduit.
 *
 * Lifecycle:
 *   @BeforeMethod → TestContext.init()   (BaseTest does this)
 *   test body     → TestContext.get().setXxx() / .getXxx()
 *   @AfterMethod  → TestContext.clear()  (BaseTest does this)
 *
 * Usage:
 *   // In an API service:
 *   TestContext.get().setAuthToken(token);
 *   TestContext.get().setUserId(createdId);
 *
 *   // In a Page Object or test step:
 *   String token = TestContext.get().getAuthToken();
 *   String email = TestContext.get().getCreatedEmail();
 *
 *   // Arbitrary key-value store for ad-hoc data:
 *   TestContext.get().store("orderId", "ORD-12345");
 *   String orderId = TestContext.get().retrieve("orderId");
 */
@Data
public class TestContext {

    private static final Logger log = LogManager.getLogger(TestContext.class);
    private static final ThreadLocal<TestContext> THREAD_LOCAL = new ThreadLocal<>();

    // ── Common shared state ───────────────────────────────────────────────────
    private String authToken;       // Bearer token after login
    private String refreshToken;
    private String userId;          // ID of user created / used in test
    private String createdEmail;    // email generated during test
    private String createdUsername;
    private String orderId;         // order created during test
    private String productId;
    private int    lastStatusCode;  // last API response status — useful for chained checks

    /** General-purpose key-value bag for any ad-hoc data. */
    private final Map<String, Object> bag = new HashMap<>();

    // ── Lifecycle ─────────────────────────────────────────────────────────────
    public static void init() {
        THREAD_LOCAL.set(new TestContext());
        log.debug("TestContext initialised for thread: {}", Thread.currentThread().getName());
    }

    public static TestContext get() {
        TestContext ctx = THREAD_LOCAL.get();
        if (ctx == null) {
            throw new IllegalStateException(
                    "TestContext not initialised for thread: " + Thread.currentThread().getName()
                    + ". Did BaseTest.setUp() run?");
        }
        return ctx;
    }

    public static void clear() {
        THREAD_LOCAL.remove();
        log.debug("TestContext cleared for thread: {}", Thread.currentThread().getName());
    }

    // ── Generic bag ───────────────────────────────────────────────────────────
    public void store(String key, Object value) {
        bag.put(key, value);
    }

    @SuppressWarnings("unchecked")
    public <T> T retrieve(String key) {
        return (T) bag.get(key);
    }

    public String retrieveString(String key) {
        Object val = bag.get(key);
        return val != null ? val.toString() : null;
    }

    public boolean has(String key) {
        return bag.containsKey(key);
    }
}
